version: "3"

services:
  zookeeper:
    container_name: demo-zookeeper
    image: 'bitnami/zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    networks:
      - internal
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: demo-kafka
    image: 'bitnami/kafka'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    networks:
      - internal
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  php:
    container_name: demo-php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./php/examples/:/var/www/html/
    networks:
      - internal
    ports:
      - "8080:8080"
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  internal:
    driver: bridge